2024-适用于 ClassIsland 1.4 Version 2.2 的 05 累计更新，适用于基于 x64 的系统 (KB1940225)
ClassIsland/ClassIsland pull request #226
Opened 2024-07-27 14:29 UTC by DryIce-cc

一些细节更新，或小 bug 修复。

2024-07-28 03:07 UTC, DryIce-cc commented
> [!warning]
> 有一些更改需要回退

2024-07-28 14:00 UTC, DryIce-cc commented
已知问题：

[feat: 闪动时钟组件的时间分隔符](https://github.com/ClassIsland/ClassIsland/pull/226/commits/a9d775e9ad0ea369f84b177ad7c42fb06ae53238)
在部分字体下，冒号和空格宽度不一致，会导致时钟组件宽度变化。
暂时可以通过开启显示秒数禁用此特性。

[feat: 显示提醒时，主界面也以半透明显示](https://github.com/ClassIsland/ClassIsland/pull/226/commits/6bd3f37b9e06b5e4290c5eabe370377f3b191480)
在显示提醒内容时，由于主界面以半透明显示，原有的窗口阴影方案无法使用。
会影响美观性，不影响使用。

2024-07-29 04:18 UTC, HelloWRC requested changes
e4ce4100 的更改导致即使没有完成欢迎向导，也可以使用应用的功能。原则上用户必须在欢迎向导同意开源许可后才能使用本应用，因此建议加回完成欢迎向导后才能操作应用功能的限制。
 
 不过这个补丁其它更改还是挺不错的👍

2024-07-29 04:36 UTC, DryIce-cc commented
> [e4ce410](https://github.com/ClassIsland/ClassIsland/commit/e4ce4100a54e2dbe0bcd8223181a30cfe7c29c84) 的更改导致即使没有完成欢迎向导，也可以使用应用的功能。原则上用户必须在欢迎向导同意开源许可后才能使用本应用，因此建议加回完成欢迎向导后才能操作应用功能的限制。
> 
> 不过这个补丁其它更改还是挺不错的👍

啊？抱歉，我以为同意 mit licence 在法律意义上没那么重要…所以就改了（）我晚点去回退

2024-07-29 14:08 UTC, DryIce-cc reviewed
已修复。不过方式稍微有点暴力（

2024-07-30 09:33 UTC, HelloWRC approved these changes

2024-07-30 09:38 UTC, merged

2024-07-30 09:38 UTC, HelloWRC commented
感谢您的贡献🤝